import Head from "next/head"
import "bootstrap-icons/font/bootstrap-icons.css" // icons bootstrap
import homeStyles from "@/styles/Home.module.css"
import Header from "./components/header/header"

export default function Home() {
  return (
    <>
      <Head>
        <title>Geren</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Header />
      <main className={homeStyles.mainContainer}>
        <div className={homeStyles.mainContainerDisclaimer}>
          <i class="bi bi-lightning-charge"></i>
          <p className={homeStyles.mainTextDisclaimer}>
            A Plataforma #1 para profissionais da saúde
          </p>
        </div>
        <div className={homeStyles.mainContainerTitle}>
          <p>Organize seu consultório. Simplifique sua rotina.</p>
        </div>
        <div className={homeStyles.mainContainerSubtitle}>
          <p>
            Gerencie agendamentos, pacientes e finanças em uma única plataforma.
            Mais tempo para cuidar, menos tempo com burocracia.
          </p>
        </div>
        <div>
          <button className={homeStyles.mainContainerButton}>
            Comece Agora
          </button>
          <button className={homeStyles.mainContainerButton}>Ver Planos</button>
        </div>
        <div className={homeStyles.mainContainerSpan}>
          <span>Sem cartão de crédito</span>
          <span>Cancele quando quiser</span>
        </div>
      </main>
    </>
  )
}
