import Head from "next/head"
import "bootstrap-icons/font/bootstrap-icons.css" // icons bootstrap
import Header from "./components/header/header"
import Main from "./components/main/main"
import Content from "./components/content/content"

export default function Home() {
  return (
    <>
      <Head>
        <title>Geren</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Header />

      <Main />
      <Content />
    </>
  )
}
