import Head from "next/head"
import "bootstrap-icons/font/bootstrap-icons.css" // icons bootstrap
import Header from "./home/components/header/header"
import Main from "./home/components/main/main"
import Content from "./home/components/content/content"
import Resources from "./home/components/resources/resources"
import Ready from "./home/components/ready/ready"

export default function Home() {
  return (
    <>
      <Head>
        <title>Geren</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Main />
      <Content />
      <Resources />
      <Ready />
    </>
  )
}
